### ISSUE TITLE
Number Not Found using Purchase method

### ISSUE THREAD

**Issue by randyrankin** [Nexmo/nexmo-php#100]
`$availableNumbers = Nexmo::numbers()->searchAvailable('US');` returns available numbers, but when I pass one of the returned numbers to `purchase()`, like this, `Nexmo::numbers()->purchase(12148567978);`, I receive `Nexmo \ Client \ Exception \ Request (404)
number not found`. Am I missing something or doing something wrong?

**Comment by randyrankin** [comment]
Consequently, `Nexmo::numbers()->cancel(11234567890)` works just fine. I just cancelled my own number ...

**Comment by mheap** [comment]
@randyrankin I've just reproduced this issue. It looks as though there's an issue with purchasing numbers when providing a string.

I'll get this fixed, but in the mean time you can purchase a number by passing a `Number` object rather than a string. Here's an example that works for me:

```php
$numbers = $client->numbers()->searchAvailable('US');
$client->numbers()->purchase($numbers[0]);
```

**Comment by randyrankin** [comment]
@mheap Thank you. Passing an array works fine and I will watch the repo for updates. In the meantime, is purchasing a Toll-Free number possible? I do not see `type` as an optional parameter in `searchAvailable()`.

**Comment by mheap** [comment]
Hey @randyrankin,

I'm not familiar with Toll-Free numbers and couldn't see anything in the documentation about them - https://developer.nexmo.com/api/developer/numbers#buy-a-number

Do you have a link to more information that I could read?

**Comment by randyrankin** [comment]
Well, yes and no. I can purchase toll-free numbers in my Nexmo dashboard, but there is no reference to them in the AP docs. Am I correct in assuming then that this is not possible? I was sure hoping to offer toll free numbers to my customers. 

![screen shot 2018-03-15 at 3 27 03 pm](https://user-images.githubusercontent.com/13204196/37489476-c1f30550-2865-11e8-89de-4623a809aa3a.png)

**Comment by mheap** [comment]
@randyrankin Sorry for the delay, it took a bit of searching to find the correct endpoints.

I've just tagged [version 1.3.1](https://github.com/Nexmo/nexmo-php/releases/tag/1.3.1) which allows you to set the number type

```
$available = $client->numbers()->searchAvailable('US', ['type' => 'landline-toll-free']);
```

**Comment by sebishabeeb** [comment]
plz help 

when i purchasing a number in nexmo then i got an error **"authentication failed"**

My code:

<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Nexmo; 
class DashboardController extends Controller
{
  
    public function index(Request $request)
    {
        $basic  = new \Nexmo\Client\Credentials\Basic(env('NEXMO_KEY'), env('NEXMO_SECRET'));
        $client = new \Nexmo\Client($basic);
        $nums =  $client->numbers()->searchAvailable('US'); 
        try
        {
         $prch = $client->numbers()->purchase($nums[0], 'US');
        } catch (\Exception $e) {
          return $e;
        }
      
    }
