### ISSUE TITLE
Call Error

### ISSUE THREAD

**Issue by sjavamaster1** [Nexmo/nexmo-php#101]
The client is created properly but the call fails

[event.zip](https://github.com/Nexmo/nexmo-php/files/1803653/event.zip)

ncaught Nexmo\Client\Exception\Request: Unauthorized in D:\Dev\TestAPI\PHPTest1\PHPTest1\vendor\nexmo\client\src\Call\Collection.php:163 
Stack trace: 
#0 D:\Dev\TestAPI\PHPTest1\PHPTest1\vendor\nexmo\client\src\Call\Collection.php(119): Nexmo\Call\Collection->getException(Object(GuzzleHttp\Psr7\Response)) 
#1 D:\Dev\TestAPI\PHPTest1\PHPTest1\vendor\nexmo\client\src\Call\Collection.php(62): Nexmo\Call\Collection->post(Array) 
#2 D:\Dev\TestAPI\PHPTest1\PHPTest1\broadcast.php(13): Nexmo\Call\Collection->create(Array) 
#3 {main} 
thrown occurred

**Comment by mheap** [comment]
Hi @sjavamaster1,

This error indicates that there is an issue with your application ID or private key. The first step would be to generate a new application and try running the code with the new credentials

**Comment by mheap** [comment]
Hi @sjavamaster1,

This error indicates that there is an issue with your application ID or private key. The first step would be to generate a new application and try running the code with the new credentials

**Comment by mheap** [comment]
@sjavamaster1 If you encountered any issues working with the Nexmo API, we'd love to hear them

**Comment by sjavamaster1** [comment]
Good Morning Michael

 

If you are running PHP on a Windows server you will need to add this to the php.ini file – make sure after you do that you restart the PHP server

 

[curl]

; A default value for the CURLOPT_CAINFO option. This is required to be an

; absolute path.

;curl.cainfo =

curl.cainfo = "C:\php\cacert.pem"

 

without having a clean cacert.pem file the Nexmo client will throw an SSL exception error

 

Someone else on the git hub had  the same issue

 

Stephanie

**Comment by mheap** [comment]
Thanks for the feedback Stephanie. This fix has been added to our README 👍  https://github.com/nexmo/nexmo-php#troubleshooting
