### ISSUE TITLE
How to test or mock Nexmo?

### ISSUE THREAD

**Issue by saleem-hadad** [Nexmo/nexmo-php#104]
Hi, 
thanks for this great package.
I've one project which uses your service and I want to know how can I mock the Client class to test the correct phone number, I don't want to send a real request to your API basically.
I know that:: don't test what don't own but at the same time I don't want to use my credit on unit tests that I have 😂
Thanks in regard.

**Comment by mheap** [comment]
Hey @saleem-hadad,

You can definitely mock the client in your code. When creating a `Nexmo\Client` instance, you can pass in a `HttpClient` to use https://github.com/Nexmo/nexmo-php/blob/develop/src/Client.php#L72
