### ISSUE TITLE
Fatal error issues

### ISSUE THREAD

**Issue by amoossssss** [Nexmo/nexmo-php#108]
Hello, I am developing a web-app that verifies user through nexmo-php.
I try to redirect users to different pages based on the response status.

I implement it by doing:
```
if($verification['status'] == "0"){
	header("Location: url1");
}
else{
	header("Location: url2");
}
```

I try to type in wrong verification code to testify my code, but things didn't go as I expected.
I got:
`
Fatal error: Uncaught Nexmo\Client\Exception\Request: The code provided does not match the expected value in /Users/amos_mac/Sites/Nexmo_test/vendor/nexmo/client/src/Verify/Client.php:158 Stack trace: #0 /Users/amos_mac/Sites/Nexmo_test/vendor/nexmo/client/src/Verify/Client.php(104): Nexmo\Verify\Client->checkError(Object(Nexmo\Verify\Verification), Array) #1 /Users/amos_mac/Sites/Nexmo_test/check.php(11): Nexmo\Verify\Client->check(Object(Nexmo\Verify\Verification), '123456') #2 {main} thrown in /Users/amos_mac/Sites/Nexmo_test/vendor/nexmo/client/src/Verify/Client.php on line 158
`

Really hope that you can help me out.
Thanks!

**Comment by mheap** [comment]
Hi @amoossssss,

The library throws an exception if the verification fails. To achieve what you're trying to do you need the following code:

```php
try {
    $client->verify()->check($verification, '1234');
    header("Location: url1");
} catch (Exception  $e) {
    header("Location: url2");
}

**Comment by amoossssss** [comment]
That works perfectly!
Thanks for your time, really appreciated.
:)

**Comment by mheap** [comment]
No worries, feel free to reach out if you have any more questions
