### ISSUE TITLE
Concatenated messages

### ISSUE THREAD

**Issue by jpmurray** [Nexmo/nexmo-php#114]
Hi there!

I just tested the reception of concatenated messages. Reading the [API reference](https://developer.nexmo.com/api/sms#inbound-sms), there should be `concat`, `concat-ref`, `concat-total`, `concat-part` included in the webhook payload, but I can't find it anywhere.

I've tried to see with `InboundMessage::createFromGlobals()` and by checking the values in the response, it just seems not to be there. Say the original message has been truncated in 3 parts, I'm receiving 3 webhooks calls, with message divided in scrambled order.

Am I missing something here?

**Comment by mheap** [comment]
Hey @jpmurray,

There don't seem to be any getters defined for those fields, but you should be able to access them using `ArrayAccess` e.g. `$obj['concat-part']`

Let me know if that doesn't work and I'll try and create a reproduction test case

**Comment by jpmurray** [comment]
So, here' the simple thing I tried:

```
<?php

$inbound = InboundMessage::createFromGlobals();

dump($inbound['concat'], $inbound['concat-ref'], $inbound['concat-total'], $inbound['concat-part']);
// All of the dumps are null.
```

I might be mistaken, but if it was available with `ArrayAcccess`, I guess it should be seen when using `getRequestData` ? I only get those: 

```
array:7 [
  "msisdn" => "XXXXXXX"
  "to" => "xxxxxxxx"
  "messageId" => "xxxxxx"
  "text" => "s. Allô ceci est un test de long sms. Allô ceci est un test de long" // sorry for being french!
  "type" => "unicode"
  "keyword" => "S."
  "message-timestamp" => "2018-08-02 15:38:34"
]
```

**Comment by mheap** [comment]
Hey @jpmurray, apologies for the delay. I've been on 🌴 

I've just tested a concatenated message and `concat-ref`, `concat-total` and `concat-part` are all accessible with the following code:

Using `getRequestData()`:

```php
$msg = InboundMessage::createFromGlobals();
$params = $msg->getRequestData();
error_log(print_r($params, true));
```

Using `arrayAccess`:

```php
$msg = InboundMessage::createFromGlobals();
$param = $msg['concat-ref'];
error_log($param);
```

This could be a network issue - could you please email support@nexmo.com with a description of the problem, a link to this issue and the phone number that you're testing with

**Comment by jpmurray** [comment]
I'm myself out of town for family matters and 🌴too. I'll be checking this as soon as I get back! ;-)

**Comment by lornajane** [comment]
Where did we get to with this? Do you think there's something we need to look at more closely?

**Comment by jpmurray** [comment]
@lornajane I'm back and forthing with support on their, their LVN are investigating but can't find anything wrong. We're looking at switching number at the moment, so still investigating!

**Comment by jpmurray** [comment]
So, further investigation lead us to discover that, even if my carrier was officially supporting concatenating message, they are sending (or forwarding, not sure) them over a network that does not, hence, not having the required "flags" to re-glue a divided SMS.

I'm gonna close the issue, since the problem relies on the network.

But, @mheap, @lornajane, I'm thinking out loud here, but I wonder if the fact that I did not see `concat` is problematic. API documentation is stating that the value is "false or "true", helping us decide if we have to go and find other value for concatenation. But in the end, here, it just did not appear at all, prompting me to think there was a problem on this side of things. Maybe I should open another issue for this?

Also, for reference, if you need to go and see details of the case with the network (support staff knows better then I do for that!), the request number on the helpdesk is 779161 !

**Comment by lornajane** [comment]
Thanks for updating us on this! Having a field that is sometimes not present does sound problematic; maybe one for Engineering to try to make the API responses consistent?
