### ISSUE TITLE
Wrong behavior with 429 error.

### ISSUE THREAD

**Issue by IIMonkeyII** [Nexmo/nexmo-php#12]
If i got 429 error, then i got response like
`<!DOCTYPE html><html><head><title>Error report</title></head><body><h1>HTTP Status 429 - message has too many concurrent requests per 1 second</h1></body></html>`.
But Client parse it as JSON and got NULL value in 
`$data = json_decode($response->getBody()->getContents(), true);`
Next Client check it and got error
`if(!$data){
            throw new Exception\Request('no message found for`' . $id . '`');
        }`
, but its wrong error, and i cant catch it by himself.
All it in Nexmo\Message\Client.

**Comment by tjlytle** [comment]
Can you provide any code to replicate?

**Comment by IIMonkeyII** [comment]
`for($i=0; $i<100; $i++) {
    echo SMSHelper::trackMessage($yourRealMessageId)['price'];
}`
If you have fast internet connection, you got 429 error on 8-10 'for' loop.
If connection not so fast, you can start few scripts in one time, you got same result.

**Comment by mheap** [comment]
Resolved via #37
