### ISSUE TITLE
How to set timeout call ?

### ISSUE THREAD

**Issue by RizkaOMG** [Nexmo/nexmo-php#120]
Hy I new abaout nexmo and i have some question It's possible to make call and ring just 20 second in PHP code?

**Comment by mheap** [comment]
To make an outbound call you can use `$client->calls()->create()` (see https://developer.nexmo.com/voice/voice-api/building-blocks/make-an-outbound-call/php)

```php

$keypair = new \Nexmo\Client\Credentials\Keypair(
    file_get_contents(NEXMO_APPLICATION_PRIVATE_KEY_PATH),
    NEXMO_APPLICATION_ID
);

$client = new \Nexmo\Client($keypair);

$call = $client->calls()->create([
    'to' => [[
        'type' => 'phone',
        'number' => TO_NUMBER
    ]],
    'from' => [
        'type' => 'phone',
        'number' => NEXMO_NUMBER
    ],
    'answer_url' => ['https://developer.nexmo.com/ncco/tts.json'],
]);
```

You'll need to keep track of the call ID somehow (e.g. `$call_id = $call->getId();`) and use that at a later time to hang up the call. This will result in an error if the call has already ended when you try and hang it up

```php
$client->calls[$call_id]->put(new \Nexmo\Call\Hangup());
```

**Comment by RizkaOMG** [comment]
Ok i got it, in my question I mean ho to end call before call answer ? Simply like ringing time just 20 second after that end call. is it possible make cal like this ?

**Comment by RizkaOMG** [comment]
I just solve my problem. I just add 'length_timer' => 3 and 'ringing_timer' => 7 and it solved. Thanks for answering my question
