### ISSUE TITLE
Accessing response from Nexmo

### ISSUE THREAD

**Issue by diamanthaxhimusa** [Nexmo/nexmo-php#125]
Hello, I have trouble getting the body data from response while doing verification. In the try block i want to return the code of $verification. 
```
try {
    $client = new \Nexmo\Client(new \Nexmo\Client\Credentials\Basic('xxx', 'xxxxxxx'));
    $verification = $client->verify()->check($verification_id, $code);
    return $verification;
} catch (\Nexmo\Client\Exception\Request $e) {
    return $e->getCode();
}
```

**Comment by lornajane** [comment]
I'm not sure if I understand what you're asking for.  Do you want to return `$code` rather than `$verification` ? The response to the `check()` call should be like this https://developer.nexmo.com/api/verify#response-2 - these fields should be available as array elements inside `$verification`.

**Comment by diamanthaxhimusa** [comment]
@lornajane Sorry if i was unclear, I want to return the $verification status code, just like in the catch block https://developer.nexmo.com/api/verify#status-values

**Comment by diamanthaxhimusa** [comment]
@lornajane That is exactly what i did and it worked! Thank you.

**Comment by lornajane** [comment]
We're delighted to help! Enjoy Nexmo :)
