### ISSUE TITLE
use Japanese is confused

### ISSUE THREAD

**Issue by huyufan** [Nexmo/nexmo-php#145]
$basic  = new \Nexmo\Client\Credentials\Basic('.........', '.........');
$client = new \Nexmo\Client($basic);
$message = $client->message()->send([
    'to' => '.........',
    'from' => 'Nexmo',
   // 'text'=>$text
    'text' => 'アイコン',
]);

hello, How to transcode display normal  thank you！

**Comment by mheap** [comment]
@huyufan You need to set `type => unicode` to send Japanese text

```
$message = $client->message()->send([
    'to' => '.........',
    'from' => 'Nexmo',
    'text' => 'アイコン',
    'type' => 'unicode'
]);
```

**Comment by lornajane** [comment]
It doesn't look like anything more is needed here, closing.
