### ISSUE TITLE
Nexmo\Insights\Client doesnt handle error responses well

### ISSUE THREAD

**Issue by runawaycoin** [Nexmo/nexmo-php#147]
Hi,

The Nexmo\Insights\Client class doesnt seem to handle error responses well.

For example
Following code example from here:
https://developer.nexmo.com/number-insight/building-blocks/number-insight-basic

```
 $basic  = new \Nexmo\Client\Credentials\Basic(NEXMO_API_KEY, NEXMO_API_SECRET);
 $client = new \Nexmo\Client($basic);
 $insights = $client->insights()->basic('07999999999');
```

The above will fail - as the number is not in internalised format (it would also be great if the basic function accepts the $additionalParams argument like the generic makeRequest function does) - but php code errors with:
```
Notice: Undefined index: national_format_number
in vendor\nexmo\client\src\Insights\Client.php (line 27)
```
Which is:
```
    $basic = new Basic($insightsResults['national_format_number']);
```

The server API response does not contain the key 'national_format_number'.

Additionally if the Nexmo API response is not 200, the code fails with this:
```
Argument 1 passed to Nexmo\Insights\Client::getException() must be an instance of Nexmo\Insights\ResponseInterface, instance of GuzzleHttp\Psr7\Response given, called in vendor\nexmo\client\src\Insights\Client.php on line 96
```

Thanks very much - i could write up a PR with these implemented / corrected if you would prefer?

**Comment by mheap** [comment]
@runawaycoin A PR would be very much appreciated!

**Comment by TheOtherBrianJ** [comment]
> The server API response does not contain the key 'national_format_number'.

Yes, it appears the API response is:
```
{
    "status": 3,
    "status_message": "Invalid request :: Not valid number format detected [ 07999999999 ]"
}
```
What should the expected behavior of the client be when the `status` is a value other than `0`? Should it throw an exception like when a non-200 http status is received? 

It's also curious to me that this request returns a 200 http status instead of 400, given the error.

**Comment by lornajane** [comment]
Thanks @TheOtherBrianJ there are some good observations here and we are always delighted to receive the pull request as well! I am looking forward to reviewing that one - I will also offer your comments about the expected status code to the API teams, but better client handling is something more immediately within our control :)
