### ISSUE TITLE
Emoji not work with Unicode + SMS in Laravel 

### ISSUE THREAD

**Issue by akasham67** [Nexmo/nexmo-php#153]
Hi,

I got problem to send emoji sms using laravel application. Every message work perfectly. But emoji not work with send message. Here is my code block:
<pre>
 $message = 'this test message 😀こんにちは世界';
 $nexmo = new \Nexmo\Client(new Basic('api_key', 'api_secret'));
 $sms_data = [
       'to' => $phone,
       'from' => $sender_id,
       'text' => $message,
       'type' => 'unicode'
     ];
$response = $nexmo->message()->send($sms_data);
</pre>

Everything work perfectly but emoji receive as ??? (what sign)

PHP Version: 7.2
Laravel Framework: 5.4
Nexmo-php: 1.0.0

**Comment by mheap** [comment]
Hi @akasham67,

Can you confirm that only the emoji shows as ???, and that all other text (including text after the emoji) is displayed correctly?

**Comment by akasham67** [comment]
Hi @mheap ,
Yes!! Only emoji shows as ???, and rest all was working fine. 
Thanks!!

**Comment by mheap** [comment]
Thanks Abul,

This sounds like a carrier issue rather than a code problem. Could you raise a ticket with support@nexmo.com containing the message IDs returned when you send the message?

**Comment by akasham67** [comment]
Hi @mheap 
I already created a support ticket on your provided email. 
Thanks!!
