### ISSUE TITLE
application.key建议

### ISSUE THREAD

**Issue by cuncle** [Nexmo/nexmo-php#157]
```
$keypair = new \Nexmo\Client\Credentials\Keypair(file_get_contents(__DIR__ . '/application.key'), 'application_id');
```
其中的 (file_get_contents(__DIR__ . '/application.key'), 'application_id') 改为'(NEXMO_APPLICATION_PRIVATE_KEY_PATH),
    NEXMO_APPLICATION_ID
)'比较容易理解。

**Comment by mheap** [comment]
Translation (via Google translate):

> Where (file_get_contents(DIR . '/application.key'), 'application_id') is changed to '(NEXMO_APPLICATION_PRIVATE_KEY_PATH),
NEXMO_APPLICATION_ID
) 'It's easier to understand.

**Comment by lornajane** [comment]
This is a nice suggestion, thanks! I created a pull request for this change.
