### ISSUE TITLE
Class 'Nexmo\Client' not found

### ISSUE THREAD

**Issue by blue-eyed-devil** [Nexmo/nexmo-php#158]
Installed via Composer, Checked file:
vendor/composer/autoload_psr4.php
and paths to nexmo are not generated

PHP Fatal error: Uncaught Error: Class 'Nexmo\Client' not found

**Comment by mheap** [comment]
@blue-eyed-devil Did you install via `composer require nexmo/php` or by adding it to `composer.json` manually?

**Comment by lornajane** [comment]
Closed due to inactivity (but re-open if if you need more info)

**Comment by lornajane** [comment]
f
