### ISSUE TITLE
Have problem with Voice Calls - Uncaught exception 'Nexmo\Client\Exception\Request - not work on Windows Datacentar 2016

### ISSUE THREAD

**Issue by NEST387** [Nexmo/nexmo-php#159]
I have problems with voice calls.

On my local PC (Windows 7+ xampp) everything works but when I migrate all to  VM Windows Datacenter 2016 (xampp and files) nothing works ? I try same configuration (xampp and on Windows 7 VM and also works on same computer where is also installed Win DataCenter 2016 VM.

The error which I get is:
Uncaught exception 'Nexmo\Client\Exception\Request' with message 'Unauthorized' in C:\xampp\htdocs\call\vendor\nexmo\client\src\Call\Collection.php:163
Stack trace:
#0 C:\xampp\htdocs\call\vendor\nexmo\client\src\Call\Collection.php(119): Nexmo\Call\Collection->getException(Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\call\vendor\nexmo\client\src\Call\Collection.php(62): Nexmo\Call\Collection->post(Array)
#2 C:\xampp\htdocs\call\indexpoziv.php(138): Nexmo\Call\Collection->create(Array)
#3 {main}
  thrown in C:\xampp\htdocs\call\vendor\nexmo\client\src\Call\Collection.php on line 163

**Comment by lornajane** [comment]
Thanks for letting us know about this problem - I know we've also discussed it on slack. As I understand it:
 - this code works on one platform without any problem
 - on another platform it does not work. <-- Is this correct, or does it work for a while and then stop?

I also note that you have an open support ticket where they are asking you to replicate the problem and to let them know what time you did that. I'll keep an eye on the additional information you are able to share there as well.

**Comment by NEST387** [comment]
HI lornajane,

Yes, as you mention above that is a problem which I can't solve and can't figure out why that is happen.
I do not know if it may be a problem because on computer where is not worked is installed Windows 2016 Datacenter ?

**Comment by lornajane** [comment]
Could you possibly answer my question: on the platform where you get this error message, does it work and then fail, or never work at all?

**Comment by NEST387** [comment]
Yes, on that computer we never success to establish voice calls (not works), but when we copy that script on other computer everything works fine.

**Comment by lornajane** [comment]
Thanks, that helps me to understand the problem. Since the code works in one place and not another, this sounds like a configuration problem rather than something wrong with the code itself, since it works in another setting.

I would suggest you compare:
* the version of PHP on both working and not-working platforms
* check that all the composer libraries are at the same (ideally newest) versions
* confirm that the API key, secret and application ID are correctly configured

Hope that helps

**Comment by lornajane** [comment]
Closed due to inactivity (but re-open if you have more information for us)
