### ISSUE TITLE
 Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate 

### ISSUE THREAD

**Issue by JanieQ** [Nexmo/nexmo-php#16]
Please help , im new to this 
I google search for some solution , and i found that i need to download cacert.pem into my file ssl 
but it doesnt seem to work .
here is my full description  of the error when i try to run send.php : 
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp\htdocs\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(180): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\nexmo\vendor\guzzle in C:\xampp\htdocs\nexmo\vendor\php-http\guzzle6-adapter\src\Promise.php on line 135

**Comment by ikatron** [comment]
We experience the same issues:
upgrade to php 7.1.12 or 7.2  stopped SMS API proper work... 
7.1.9 and bellow good!
Used on multiple VMs
Downgrade to 7.1.9 the same code... no problem again
Used composer
OS Win 10 Pro Clear installed just default PHP package... no any other problems with other complex PHP codes...



PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in
nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
nexmo\vendor\php-http\guzzle6-adapter\src\Promise.php on line 135
nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(179): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))

**Comment by mheap** [comment]
I've added a note to the README. Thanks for helping debug via the Nexmo Community Slack @ikatron https://github.com/nexmo/nexmo-php#troubleshooting
