### ISSUE TITLE
Security warning about composer.json

### ISSUE THREAD

**Issue by repat** [Nexmo/nexmo-php#167]
We're using [roave/security-advisories]( https://packagist.org/packages/roave/security-advisories) to not accidentally install PHP packages with known security issues. When installing `nexmo/laravel-notification` I got a warning and couldn't install. Following this further down the rabbit hole I got:

> nexmo/laravel-notification => nexmo/laravel => nexmo/client => zendframework/zend-diactoros: ^1.3

Seems like it's fixed in `zendframework/zend-diactoros: ^1.8.4`, at least according to roave, I didn't do that much research. Technically it should actually install 1.8.6 but doesn't if you already installed version 2.x. Maybe this could be prevented by putting `^1.8.5` in this `composer.json`?

**Comment by lornajane** [comment]
Thanks for flagging this for us! I'll take a look

**Comment by lornajane** [comment]
Should be fixed in 1.8.1. Thanks for pointing this out, we really appreciate it :)
