### ISSUE TITLE
difference between verify and just sending an sms

### ISSUE THREAD

**Issue by MrMoronIV** [Nexmo/nexmo-php#172]
What's the difference between sending a verify SMS and just sending an SMS with a code and verify the code yourself?

**Comment by lornajane** [comment]
Verify adds some extra features such as following up with a voice call (can be useful on some mobile networks), but if those aren't all that useful for your use case and you'd be confident to implement it yourself then you should totally go ahead and just send an SMS with a code. Does that help?

**Comment by MrMoronIV** [comment]
Are there specific countries that have difficulties with receiving SMS then? Since I'm in Europe I expect every SMS to always arrive, so a voice call is not needed. Is that a correct assumption?

On the other hand, there aren't any costs for using Verify when people put in a fake number right?

**Comment by lornajane** [comment]
SMS is pretty reliable in Europe, yes. Pricing on Verify is changing in the coming weeks but as things stand, customers are only charged when a number is verified. Hope that helps you decide what fits your needs!
