### ISSUE TITLE
Add throttling support?

### ISSUE THREAD

**Issue by mheap** [Nexmo/nexmo-php#177]
Should we add support for throttling endpoints that have rate limits? https://github.com/hamburgscleanest/guzzle-advanced-throttle looks like a reasonable solution

**Comment by arubacao** [comment]
IMO if you allow custom clients (e.g. #164) I don't feel like this is necessary for this package. Maybe a tutorial on how to create a custom client that is capable of throttling is sufficient. 
However, in the same context, maybe revise this part of the code: https://github.com/Nexmo/nexmo-php/blob/2f79f67f24225ea627ee14578e98c96276cdd4c5/src/Message/Client.php#L63-L69
Rather fail the request than have a never ending retry loop that cannot really be controlled anymore (and potentially cost money(?)).

**Comment by lornajane** [comment]
I think that we probably don't want to add throttling or retries at the library level, but I think we could improve the error handling which would make it easier for users to understand if something didn't work and take whatever action makes sense in their context? The point about getting stuck in the endless retry loop is a good one!

**Comment by dragonmantank** [comment]
As of v2.2.0, there is now a specific `Nexmo\Client\Exception\ThrottleException` that is thrown.

In the few places it made sense or we already had support, the Nexmo client now watches for this specifically and handles it. This is specifically in the SMS and Numbers where it is incredibly easy to hit the throttle limit without knowing.
