### ISSUE TITLE
php api 500 error

### ISSUE THREAD

**Issue by topart1** [Nexmo/nexmo-php#18]
in my local server i did all the instructions that appear in github and it's worked great.
but now when i moved it to my cloud server it's give me 
500 - Internal server error. 
you can see it here
http://control-center.perspective-media.me/modules/sms/examples/send.php
I copy all my php folder from local to cloud so it's the same setting and the same files
just for the testing i gave all permission to the sms folder.
i tried everything and i don't get nothing.
the only thing that i get in error log:
PHP Warning: PHP Startup: pthreads: Unable to initialize module
Module compiled with module API=20151012
PHP compiled with module API=20131226
These options need to match
in Unknown on line 0
please heip

**Comment by tjlytle** [comment]
This seems to be an issue with the pthreads extension; however, I'm not sure what dependency in the library requires that extension. Are you sure this error happens *only* when using the library, and not with any php file in the same environment?

**Comment by topart1** [comment]
Im sure 100%

 

To be 100% I did the following tests:

 

 

1.       Try on another vm and it worked 

2.       Test on few php versions

3.       Test on local url and few other domain

4.       Test on few location of folders with all permissions

 

In my local server it's worked so I copy the same setting and the same php folder to my remote cloud and didn't work.

 

When I tried to do it locally url I get this error on the browser.

 

C:\php\v5.6\php-cgi.exe - The FastCGI process exited unexpectedly

 


Module

   FastCgiModule


Notification

   ExecuteRequestHandler


Handler

   php-5.6.24


Error Code

   0x000000ff

 

 

I spent on it for hours and didn't find solutions.

 

Please help me.

I can send you php info if you need but to private mail.

 

 

Thank you for your replay

 

Avi

**Comment by tjlytle** [comment]
Pretty sure that error has something to do with your configuration. However, it's just a warning, so your script should still run. Are you getting any other errors in your error log (not the browser)? Perhaps put some debug logging around the use of the library?
