### ISSUE TITLE
Manual installation of NEXMO libraries on server

### ISSUE THREAD

**Issue by EsmonDx** [Nexmo/nexmo-php#187]
Hi.I need to send SMS via NEXMO using PHP calls originating from my provider's server.
I am not familiar with Composer. 
Could you please explain which files I should manually copy onto my Server and how to link them and make the SMS send calls? Many thanks

**Comment by lornajane** [comment]
The library is intended to be used with Composer, I would strongly recommend that you install and use it (https://getcomposer.org). The library relies on other libraries as well, and Composer installs everything in the correct place and sets up the autoloader; it would be difficult to get this right when doing things manually.

Alternatively you could call the API directly from your PHP application, and not use the library at all. Check out the API reference for our SMS API for more information. https://developer.nexmo.com/api/sms

If you have more questions for us, please feel free to get in touch - but I'll close this issue for now.

**Comment by EsmonDx** [comment]
Thanks lornajane. My issue is that I don't get conceptually how I should arrange the files for Composer..  

I am not working on a virtual server or anything like that. I simply have a php file on my provider's server which, when called, triggers the SMS send via Nexmo. Would Composer upload the required libraries onto the server? My impression is that load them only locally. Could you please explain the correct way to proceed? Many thanks!

**Comment by lornajane** [comment]
Ideally you'd run the composer command on the server as part of the deployment process. This doesn't sound like it's something you'd already have in place though, and I'm guessing you are probably using a fairly old version of PHP? I'd probably recommend you use PHP to call the API directly, via either curl if it is installed, or streams. The SMS API is not especially complicated if you do need to handle it directly.

**Comment by EsmonDx** [comment]
Loranjane, I've got PHP 7.2.1 but have no idea then on how to run Composer from the server. 
Ok to make direct API calls then. Could you please send me a simple sample code to send an SMS via curl directly in PHP?

**Comment by lornajane** [comment]
We assume a certain level of API knowledge from people who want to use our APIs, and since our PHP library is our recommended and supported solution, our examples all use that. You could try googling for an example of calling an API from PHP to get you started?
