### ISSUE TITLE
is not an array in

### ISSUE THREAD

**Issue by topart1** [Nexmo/nexmo-php#19]
array_merge(): Argument #2 is not an array in .....src\Message\Message.php on line 61

**Comment by tjlytle** [comment]
Can you provide the code that calls this (or a stack trace if you're not calling it directly)?

**Comment by topart1** [comment]
Hi

Thank you for your replay

 

 

You mean this one? And I attach trace…

require_once 'vendor/autoload.php';

 

//create client with api key and secret

$client = new Nexmo\Client(new Nexmo\Client\Credentials\Basic("***", "******"));

$val="If you got this msg please tell me";

//send message using simple api params

$message = $client->message()->send([

     'to' => *****,

                  'type' =>'unicode',

                  'from' => *****,

      'text' => $val

]);

 

 

 

//array access provides response data

echo "Sent message to " . $message['status'] . ". Balance is now " . $message['remaining-balance'] . PHP_EOL;

**Comment by mheap** [comment]
Hi @topart1,

I managed to send an SMS fine with the following code:

```
<?php

require_once 'vendor/autoload.php';

//create client with api key and secret
$basic  = new \Nexmo\Client\Credentials\Basic('API_KEY', 'API_SECRET');
$client = new Nexmo\Client($basic);

$val="If you got this msg please tell me";

//send message using simple api params

$message = $client->message()->send([
    'to' => 'TO_NUMBER',
    'type' =>'unicode',
    'from' => 'FROM_NUMBER',
    'text' => $val
]);

//array access provides response data
echo "Sent message to " . $message['to'] . ". Balance is now " . $message['remaining-balance'] . PHP_EOL;
```

Please let us know if you're still having any issues
