### ISSUE TITLE
v2: Inconsistent account responses

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-php#193]
I'm using this code

```php
$response = $client->account()->getConfig();
print_r($response->data);

$response = $client->account()->getBalance();
print_r($response->data);
```
The first `print_r()` outputs all the config on my account. The second one causes an exception

```
PHP Fatal error:  Uncaught Error: Cannot access protected property Nexmo\Account\Balance::$data
```

The `data` property should be always accessible (or always protected I guess). Also we use these examples in the usage docs in the README (see https://github.com/Nexmo/nexmo-php#check-your-balance)

**Comment by dragonmantank** [comment]
Corrected in 5d9f689cf1c32b7271c6690c133be7364dbc18da

What happened was I added tests for that object, and `$this->data` was not written as part of the class (looks like it was always just added as a property via PHP's wonderful "sure, that's a property!" assignment), so I added it as an explicit property. From the looks of the object that `$this->data` property was only accessed via methods, so I set it `protected`. 

Changed it `public` to preserve behavior but still keep the property documented.
