### ISSUE TITLE
How to disable CURLOPT_SSL_VERIFYPEER in Nexmo client?

### ISSUE THREAD

**Issue by mostafasoufi** [Nexmo/nexmo-php#20]
Hello @tjlytle,

How to disable `CURLOPT_SSL_VERIFYPEER` in the Curl? i can disable this with hard code.

Line 327 - CurlFactory.php
`$conf[CURLOPT_SSL_VERIFYPEER] = false;`

But i want disable on the `Nexmo\Client`

Regards

**Comment by tjlytle** [comment]
You can pass a second argument when creating a `new Nexmo\Client($credentials, $httpClient)`. You can use that to configure Guzzle however you'd like (disable SSL verify), just make sure that you wrap the Guzzle instance in the Http Plug adapter:

    $client = new \Http\Adapter\Guzzle6\Client($configuredGuzzleInstance);

**Comment by tjlytle** [comment]
For what it's worth, you should also be able to use any other HTTPlug adapter. I need to make that a bit more first class, but it _should_ work (haven't tested it though).

**Comment by kjjdion** [comment]
Heres complete code example (thanks to @tjlytle):

	$adapter_client = new Http\Adapter\Guzzle6\Client(new Http\Adapter\Guzzle6\Client(['verify' => false]));
	$nexmo_client = new Nexmo\Client(new Nexmo\Client\Credentials\Basic($api_key, $api_secret), [], $adapter_client);
	$message = $nexmo_client->message()->send([
	    'to' => $to,
	    'from' => $from,
	    'text' => $text,
	]);
