### ISSUE TITLE
Can I send whatsapp Messages?

### ISSUE THREAD

**Issue by SergioAraya** [Nexmo/nexmo-php#201]

**Comment by dragonmantank** [comment]
At this time we do not have support for our "Messages" or "Dispatch" APIs directly in the SDK, as they are currently in Beta. You can, however, directly hit our API through an HTTP client like Guzzle.

To use WhatsApp, you will need a supporting WhatsApp Business number. We do provide sales help with getting one set up, but cannot guarantee approval. More information on using WhatsApp can be found here: https://developer.nexmo.com/messages/concepts/whatsapp

I hope that helps!
