### ISSUE TITLE
Replace zendframework/zend-diactoros with laminas/laminas-diactoros

### ISSUE THREAD

**Issue by jaikdean** [Nexmo/nexmo-php#206]
The `zendframework/zend-diactoros` packages has been marked as abandoned as of the end of 2019. There is a community-supported open source continuation in `laminas/laminas-diactoros`. Composer is now showing warnings about this on `composer install`, so we should update to depend on the Laminas package rather than the Zend one.

The new package is under a different namespace so will require code updates, but means there won't be any conflicts if projects otherwise depend on the Zend package.

**Comment by lornajane** [comment]
Thanks for pinging us with this information, I think we should definitely make this change. Pull requests always welcome but just opening the issue is also helpful as it gets it on our radar :)

**Comment by dragonmantank** [comment]
As @lornajane mentioned, thank you for the issue and PR! I'm going through and figuring out when best to get this pushed out, but rest assured this is appreciated!

**Comment by andrei-dascalu** [comment]
Also looking forward to the update!

**Comment by SDekkers** [comment]
Any update on this?

**Comment by dragonmantank** [comment]
This will be going out as a minor release here soon, I've made sure we aren't returning this anywhere.

In the meantime, it is simply a warning, so the Nexmo client will continue to work just fine, and Composer will continue to understand how to pull down the old `zendframework` namespace.

**Comment by jaikdean** [comment]
Any news on getting this merged?

**Comment by dragonmantank** [comment]
*crosses fingers* The v3 SDK should hopefully be soon. I'm going through the final rounds of cleanup.

I'm lumping it in the new release only because we did expose the requests and responses in a lot of objects, so anyone that did type hinting or used them will need to update their code.

**Comment by dragonmantank** [comment]
Handled in v2.2.0.
