### ISSUE TITLE
application.key and application_id

### ISSUE THREAD

**Issue by pedromazala** [Nexmo/nexmo-php#21]
Hey there. Where do I create an application to get the key and id? I didnt found this...

**Comment by leggetter** [comment]
@pedromazala - when you're working with the Nexmo Voice API you need to create Nexmo Applications within the Nexmo platform. The easiest way IMO to do that is to use the [Nexmo CLI](https://github.com/nexmo/nexmo-cli).

Install (you'll need Node installed):

```sh
npm install nexmo-cli -g
```

*Note: you may need to prefix `sudo` if you get an error related to permissions*

Once installed set it up with your Nexmo API Key and secret. You can now get this from the [Nexmo Dashboard getting started page](https://dashboard.nexmo.com/getting-started-guide) (at the top):

```sh
nexmo setup <api_key> <api_secret>
```

From there you can create a Nexmo Application. As part of that you'll get a Application ID, Public Key and Private Key. Run this command to create an application and save the private key (you only get this upon initial app creation so you have to save it):

```sh
nexmo app:create "Test Application 1" http://example.com http://example.com  --keyfile private.key 
```

The output from this command will also provide you with the Application ID and public key. It's likely you'll want to save these key files and to a configuration file within your app. You can then use it with the library along with the key files.

You can find out more about he params in the above command by running `nexmo app:create --help`.

I hope this helps you progress with your app development. Please let me know.

**Comment by pedromazala** [comment]
I tried do this.. But: 

```bash
root@ea68d6555783:/app# nexmo setup 76*****c 4**************b
No existing config found. Writing to new file.
Credentials written to /root/.nexmorc

root@ea68d6555783:/app# nexmo app:create "Test Application 1" http://example.com http://example.com  --keyfile private.key
Application created: undefined
/usr/lib/node_modules/nexmo-cli/lib/response.js:195
        _this9._writeKey(flags.keyfile, response.keys.private_key);
                                                     ^

TypeError: Cannot read property 'private_key' of undefined
    at /usr/lib/node_modules/nexmo-cli/lib/response.js:195:54
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/nexmo-cli/node_modules/nexmo/lib/HttpClient.js:105:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Do you know what can be?

And i have to give a unique answer and event URL to each application?

**Comment by leggetter** [comment]
@pedromazala - 

> Application created: undefined

There's was problem with the Application API. This has no been resolved. You should no longer see this problem.

> And i have to give a unique answer and event URL to each application?

This is recommended, yes. A Nexmo application tends to have a one-to-one mapping with the application that you are building so it is mostly the case that the `answer_url` and `event_url` will be unique for the Nexmo application and your application.

I hope this helps.

**Comment by tjlytle** [comment]
@pedromazala This also may be helpful, you can create an application [using the client library as well](https://github.com/Nexmo/nexmo-php#creating-an-application). The private key is only returned from the `POST` that creates the application, so you'll have to store `$application->getPrivateKey()` after it's created.

**Comment by pedromazala** [comment]
Ok thanks.

But, about one-to-one mapping, can I do a redirect after user give me a information? Something like `Press 1 to do this` and after user press he is redirected to another url that have another JSON to read.. Is that possible?

Im sorry about the two questions in one issue.

**Comment by leggetter** [comment]
You can override the `event_url`/`eventUrl` with specific actions. For example, you can specify an `event_url` for an `input` action:

```json
[
  {
    "action": "talk",
    "text": "Please enter a digit"
  },
  {
    "action": "input",
    "eventUrl": ["https://example.com/ivr"]
  }
]
```
https://docs.nexmo.com/voice/voice-api/ncco-reference#input

When the `eventUrl` is called you can return an NCCO to inform Nexmo how to handle that call based on the user input. e.g. if they press 1 then you could [`connect`](https://docs.nexmo.com/voice/voice-api/ncco-reference#connect) them to a phone. If they press 2 then you could [`stream`](https://docs.nexmo.com/voice/voice-api/ncco-reference#stream) audio to them.

**Comment by pedromazala** [comment]
Thanks a lot

**Comment by tjlytle** [comment]
Going to close this thread for now. @pedromazala you can join the [Nexmo community slack](http://nexmo-community-invite.herokuapp.com/) and continue the conversation there (just mention @tjlytle or @leggetter there).

**Comment by pedromazala** [comment]
I'm not getting invite in posted link... My e-mail is `pedroh.mazala (at) gmail.com`
