### ISSUE TITLE
How to know is sms delivered or not?

### ISSUE THREAD

**Issue by stojankukrika** [Nexmo/nexmo-php#214]
Hi I like to get info is sms delivered or not. How to get that info?

**Comment by dragonmantank** [comment]
We do offer Delivery Receipt confirmations. More information on the receipts can be found at https://developer.nexmo.com/messaging/sms/guides/delivery-receipts.

You will need to set up a Delivery Receipt webhook on your account to receive these notifications. If you log into [Customer Dashboard](https://dashboard.nexmo.com/) and go under your account settings, you can set a URL that can accept the delivery receipts. We will then send a payload to that URL whenever a delivery receipt is issued from the provider.

Setting up the webhook is something that will need to be done in your application, however, as it is just incoming data. There is also no specific need for the SDK to receive or read this data.

**Comment by stojankukrika** [comment]
Looks awesome! Tnx a loot @dragonmantank !

**Comment by stojankukrika** [comment]
I have a problem, maybe someone has solution for it... When I send SMS it's faster get a response on webhooks then I write in local DB message-id. So can't get status again :) Can you have some idea?
