### ISSUE TITLE
Facek

### ISSUE THREAD

**Issue by facek-code** [Nexmo/nexmo-php#225]
$sms = $nexmo->message->send(08985893913);
$response = $sms->getResponseData();
$total = 0.0;
foreach ($response['messages'] as $message) {
    $total += (float)$message['message-price'];
}

**Comment by lornajane** [comment]
Thanks for pasting some code in our issue tracker. Are you having a problem? Can you tell us a bit more about what you're trying to do so we can help?

**Comment by dragonmantank** [comment]
Hello! Since there hasn't been any movement on this, I'm going to close it out.

It looks similar to #221 as well, and I've updated that ticket with some more information if that helps. If you are still having issues, feel free to re-open this issue.
