### ISSUE TITLE
PHP + website no longer sends text

### ISSUE THREAD

**Issue by cpgb85** [Nexmo/nexmo-php#226]
The tool on the site to send a test message and the PHP code no longer send text messages to my phone.

**Comment by dragonmantank** [comment]
It looks like there are currently some service degradation, according to https://www.nexmostatus.com/. I would keep track of that website for the most up-to-date information regarding the two service areas that are marked for maintenance/outages. 

If you are outside of those areas, please re-open this issue and let me know which tool and code you are looking at.
