### ISSUE TITLE
in Nexmo\Client, api call annotated twice.

### ISSUE THREAD

**Issue by t-nakamura** [Nexmo/nexmo-php#234]
https://github.com/Nexmo/nexmo-php/blob/0064fb85b775b23e1bf68b9d8acf706a0f6bc4bd/src/Client.php#L34-L45

```
 * @method \Nexmo\SMS\Client sms() L36, L43
 * @method \Nexmo\Verify\Client  verify() L37, L44
```

at version 2.2.0 release.

**Comment by dragonmantank** [comment]
Thanks for catching that! This typo is fixed in 2.2.1
