### ISSUE TITLE
whether the application which i create will be timeout or  be detroyed 

### ISSUE THREAD

**Issue by cycman** [Nexmo/nexmo-php#28]
i am a company's devlopser i want to know whether the application which i create will be timeout or  be detroyed  this is very important to me please commit to me as soon as you can 
my email is cclikecode@gmail .com

**Comment by tjlytle** [comment]
@cycman The application you create will be around until you [delete it with the API](https://docs.nexmo.com/tools/application-api/api-reference#delete).
