### ISSUE TITLE
this is very important to me 

### ISSUE THREAD

**Issue by cycman** [Nexmo/nexmo-php#30]
hello man 
threre is a very important question to me 
i wan to know the nexmo'limit  when i send sms and call
1000/day ?  or other ?
can you tell me the limit 
and  what will happens to me 
when i reachethe limit

**Comment by tjlytle** [comment]
Here's the [best place to find that answer](https://help.nexmo.com/hc/en-us/articles/203993598-What-is-the-Throughput-Limit-for-Outbound-SMS-). On rate limiting, the client library will [handle that automatically](https://github.com/Nexmo/nexmo-php/blob/master/src/Message/Client.php#L63-L68), and back off as needed.
