### ISSUE TITLE
Bulk send

### ISSUE THREAD

**Issue by mostafasoufi** [Nexmo/nexmo-php#31]
Hi @tjlytle 

It's possible to send bulk?

Regards

**Comment by tjlytle** [comment]
Yup, just loop through your list. :)

The API doesn't support multiple recipients, but you can certainly make multiple send requests. The client library will rate limit accordingly.

**Comment by mostafasoufi** [comment]
So getting timeout error to send a lot number with loop method. How many support with this method?

**Comment by mostafasoufi** [comment]
This package is good option for handler this issue but I can't use that because i want use in [my plugin](https://github.com/veronalabs/wp-sms) on the wordpress.

Maybe [WP Background Processing](https://github.com/A5hleyRich/wp-background-processing) is better for wordpress.

Thanks for your help.
