### ISSUE TITLE
Invalid parameter found: null

### ISSUE THREAD

**Issue by RamzyVirani** [Nexmo/nexmo-php#35]
Hi,
I am using `nexmo-laravel ` package in my application. When I try to call `\Nexmo::verify()->trigger($verification_code)` where `$verificaiton_code` is a valid code returned from `\Nexmo::verify()->start()` I get `Invalid parameter found: null` exception with status code 3 from `vendor\nexmo\client\src\Verify\Client.php:158` which I believe returns whatever `error_text`  and `status` is returned from Nexmo API. However, I do receive a call with the verification code.

Can someone help me out.

**Comment by mheap** [comment]
Hi @RamzyVirani,

Could you provide the code that you're using in your controller so that we can try and reproduce this issue?

Thanks, Michael

**Comment by RamzyVirani** [comment]
Thanks for your late reply, I have moved on from the project.
