### ISSUE TITLE
Fatal error: Class 'Nexmo\Client\Credentials\Basic' not found 

### ISSUE THREAD

**Issue by ahmedhashmi21** [Nexmo/nexmo-php#40]
Hi, I am very new in this integration. i don't how to implement. I was looking for web api but i don't how to handle it.
I have downloaded nexmo php library and following as mentioned in document. can anyone guide me with easy simple steps. 

I need to integrate simply but it is showing class not found fatal error . please help me in this. thanks in advance,

**Comment by mheap** [comment]
Hi @ahmedhashmi21,

Have you [installed the library](https://github.com/Nexmo/nexmo-php#installation) using Composer?

**Comment by ahmedhashmi21** [comment]
No,  i didn't use that

**Comment by ahmedhashmi21** [comment]
Can u please help me or guide to install the library using composer, i am very new to this. I just downloaded git library , changed kies in file. please help me in this.

**Comment by mheap** [comment]
Whilst you can download the library directly, you need to use a PSR-4 compatible autoloader. In most cases, it's easier to use composer.

Please see the following links for instructions on how to install Composer:

* [Linux/Unix/OSX](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx)
* [Windows](https://getcomposer.org/doc/00-intro.md#installation-windows)

**Comment by ahmedhashmi21** [comment]
Hi Michael, thanks for support. i have installed compose and then nexmo-git library using composer. vendor folder is created with all other required libraries and files. i copied vendor folder to my apache server directory, change kies in file and then execute send.php file. 
then i gave me following error.

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\xampp\htdocs\sites\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 D:\xampp\htdocs\sites\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\xampp\htdocs\sites\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\xampp\htdocs\sites\nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(180): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 D:\xa in D:\xampp\htdocs\sites\nexmo\vendor\php-http\guzzle6-adapter\src\Promise.php on line 135

**Comment by ahmedhashmi21** [comment]
Is there any step by step guide for beginners, please help me in this.
Thanks in advance.

**Comment by mheap** [comment]
Could you explain what you're trying to accomplish with Nexmo? Once we know we can help out

**Comment by ahmedhashmi21** [comment]
I just need to do two things.
1. To send sms on given number using php api.
2. To send recorded/text to speech voice call to customer (one way call).

I have application where someone shows interest in product that time we send sms to user and also voice call.  voice call is one way call, this is to alert user. user will receive call and hear information about product. thats it.

**Comment by mheap** [comment]
Hi @ahmedhashmi21,

If you could join the [Nexmo Community Slack](https://developer.nexmo.com/community/slack) organisation, our developer relations team will be available to assist you with any issues you may be facing.

I'm going to close this ticket and we can continue the discussion in a more realtime setting on Slack.
