### ISSUE TITLE
Add User-Agent Header to requests

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-php#6]
_Hands up_ - I only did a quick search in the source via the GitHub search. But it didn't show `User-Agent` in there.

As per [the spec](https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#reporting) we want to use this header to track usage of the library.

**Comment by tjlytle** [comment]
Yeah, I know it's missing, will be releasing that and a few other niceties soon.
