### ISSUE TITLE
Composer and Prestashop 1.7

### ISSUE THREAD

**Issue by olivier-nexmo** [Nexmo/nexmo-php#77]
I'm having trouble to install Nexmo client using composer with Prestashop 1.7 installation:

composer require nexmo/client:@beta
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install nexmo/client 1.0.0
    - Conclusion: don't install nexmo/client 1.0.0-beta4
    - Conclusion: don't install nexmo/client 1.0.0-beta3
    - Conclusion: don't install nexmo/client 1.0.0-beta2
    - Conclusion: don't install nexmo/client 1.0.0-beta1
    - Conclusion: don't install nexmo/client 0.4.0
    - Conclusion: remove guzzlehttp/guzzle 5.3.1
    - Installation request for nexmo/client @beta -> satisfiable by nexmo/client[0.3.0, 0.4.0, 1.0.0, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.1
    - nexmo/client 0.3.0 requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[v1.0.0, v1.1.0, v1.1.1].
    - php-http/guzzle6-adapter v1.0.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0].
    - php-http/guzzle6-adapter v1.1.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0].
    - php-http/guzzle6-adapter v1.1.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.3, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 5.3.1].
    - Installation request for guzzlehttp/guzzle (locked at 5.3.1) -> satisfiable by guzzlehttp/guzzle[5.3.1].

Installation failed, deleting ./composer.json.

**Comment by mheap** [comment]
Hi @olivier-nexmo,

We've recently tagged a stable version of Nexmo's PHP client and it looks as though we haven't updated all of the instructions yet.

Try running `composer require nexmo/client` instead

Cheers, Michael

**Comment by olivier-nexmo** [comment]
Thank you, Michael.

I'm still facing issues:

composer require nexmo/client
Using version ^1.0 for nexmo/client
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nexmo/client ^1.0 -> satisfiable by nexmo/client[1.0.0].
    - Conclusion: remove guzzlehttp/guzzle 5.3.1
    - Conclusion: don't install guzzlehttp/guzzle 5.3.1
    - nexmo/client 1.0.0 requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[v1.0.0, v1.1.0, v1.1.1].
    - php-http/guzzle6-adapter v1.0.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0].
    - php-http/guzzle6-adapter v1.1.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0].
    - php-http/guzzle6-adapter v1.1.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.3, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 5.3.1].
    - Installation request for guzzlehttp/guzzle (locked at 5.3.1) -> satisfiable by guzzlehttp/guzzle[5.3.1].


Installation failed, deleting ./composer.json.

I guess it's because of the guzzlehttp version. I've tried to update it, but it failed :-(

composer require guzzlehttp/guzzle:~6.0
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - guzzlehttp/log-subscriber 1.0.1 requires guzzlehttp/guzzle ~4.0 | ~5.0 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - guzzlehttp/log-subscriber 1.0.1 requires guzzlehttp/guzzle ~4.0 | ~5.0 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - guzzlehttp/log-subscriber 1.0.1 requires guzzlehttp/guzzle ~4.0 | ~5.0 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for guzzlehttp/log-subscriber (locked at 1.0.1) -> satisfiable by guzzlehttp/log-subscriber[1.0.1].

Installation failed, deleting ./composer.json.

**Comment by mheap** [comment]
Hi @olivier-nexmo,

It looks as though you've hit an edge case that we're currently working on related to multiple versions of Guzzle. Does Prestashop use Guzzle 5.x?

**Comment by scheMeZa** [comment]
Prestashop does indeed use Guzzle 5.3.1.

**Comment by mheap** [comment]
Thanks for confirming @scheMeZa 

Once we resolve #5 this will be fixed
