### ISSUE TITLE
Callback and client-ref

### ISSUE THREAD

**Issue by olivier-nexmo** [Nexmo/nexmo-php#84]
Hi, any ETA to get callback, status-report-req and client-ref parameters supported by the library?

Thank you

**Comment by mheap** [comment]
Could you point me to the relevant documentation?

**Comment by olivier-nexmo** [comment]
https://developer.nexmo.com/api/sms#parameters (note: client-ref isn't listed in the request parameters, I've raised a documentation bug for it)

**Comment by mheap** [comment]
The client supports all of these parameters. I've updated the README to reflect this.

Here's an example of sending a message with client-ref and DLR:

```
$text = new \Nexmo\Message\Text(NEXMO_TO, NEXMO_FROM, 'Test message using PHP client library');
$text->setClientRef('test-message')
     ->requestDLR()
     ->setCallback('http://example.com');
$client->message()->send($text);
```
