### ISSUE TITLE
Missing params for `account/numbers` search

### ISSUE THREAD

**Issue by arubacao** [Nexmo/nexmo-php#87]
Besides the number, one cannot define any other params like `size`.

[Method `searchOwned($number = null)`](https://github.com/Nexmo/nexmo-php/blob/e03dc4c0e71075c348f194955b6ed01e0d833ada/src/Numbers/Client.php#L127)

[API docs: list-owned-numbers](https://developer.nexmo.com/api/developer/numbers#list-owned-numbers)

**Comment by mheap** [comment]
Thanks for raising this @arubacao! Do you fancy reviewing the PR that fixes this?
 https://github.com/Nexmo/nexmo-php/pull/88/files

Once it's reviewed I can tag and release a new version
