### ISSUE TITLE
::class is not valid

### ISSUE THREAD

**Issue by imcery** [Nexmo/nexmo-php#9]
Using class as a name of a constant is available in PHP 5.5 only.

Here is the example of the error message:

exception 'yii\base\ErrorException' with message 'syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'' in
/www/my/vendor/nexmo/client/src/Message/Client.php:154

So it's better to change ::class to get_class()

**Comment by tjlytle** [comment]
5.4 has been end of life for more than a year (in fact, 5.5 is ending security updates in a few days), so I probably should set the `composer.json` target to a higher version. 

That said, if `::class` is the only 5.5 features we're current using, that's easy enough to take out. I'll take a look.

**Comment by mheap** [comment]
Ideally, we'd like to only support versions of PHP that are being actively maintained. However, we understand that not everyone can upgrade their version of PHP easily.

We've come to a compromise which allows us to use modern tools (`::class` syntax, modern versions of PHPUnit) without dropping support for PHP 5. Going forward, we'll only be supporting PHP 5.6+ (see https://github.com/Nexmo/nexmo-php/commit/880a3672c42660730aa74059e911140f1968a8f6)

Thanks for raising this issue, and let us know if there's anything we can do to help in the future
