### ISSUE TITLE
Is there support for verifying signed messages?

### ISSUE THREAD

**Issue by rjmackay** [Nexmo/nexmo-php#90]
Its not clear from the docs how or if you should verify inbound message signatures. Is this possible? or something I need to implement myself?

**Comment by mheap** [comment]
Hi @rjmackay, apologies for the delay in getting back to you.

Verifying signed messages is something that you'll need to implement yourself for now unfortunately. If you're willing to implement that functionality and submit a pull request to the library, that would be amazing!

Cheers, Michael

**Comment by lornajane** [comment]
This feature is now complete and documented in the README. Thanks again for asking about it (I realise it has been a while)
