### ISSUE TITLE
Read Client::VERSION from composer.json

### ISSUE THREAD

**Issue by mheap** [Nexmo/nexmo-php#91]
We currently have to remember to update `Client::VERSION` on each release. We could use https://github.com/Ocramius/PackageVersions to do it dynamically instead

**Comment by mheap** [comment]
This is currently blocked whilst we need to support PHP 5.6

**Comment by lornajane** [comment]
I note that the minimum requirement for Ocramius/PackageVersions is now PHP 7.1 so I'm not sure if we can hold out for this. It's neat, because it's a composer plugin, but Marcus doesn't have any intention of supporting a wide range of PHP versions as far as I can tell.

**Comment by lornajane** [comment]
I've now engaged my brain, PHP 7.0 goes out of security fix support before PHP 5.6 so will be moving to a minimum of 7.1 anyway. As you were.
