### ISSUE TITLE
Beginner in Nexmo - Need Step by step guide

### ISSUE THREAD

**Issue by ahmedhashmi21** [Nexmo/nexmo-php#92]
Hi Team,

I am very beginner to use Nexmo API. 
Please help step by step guide to get started with Nexmo. first let me explain you what I have done till now.

1. I have installed nexmo in my localhost directory using composer.
2. I have add sms.php file in that folder and update API keys.

But It gives following error :
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\xampp\htdocs\sites\efb_nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 D:\xampp\htdocs\sites\efb_nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\xampp\htdocs\sites\efb_nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\xampp\htdocs\sites\efb_nexmo\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(180): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory) in D:\xampp\htdocs\sites\efb_nexmo\vendor\php-http\guzzle6-adapter\src\Promise.php on line 135

I need to test Nexmo only outbound SMS and outbound Text-to-Speech Call. post successfull testing I need to upload that directory on production server for final testing and implementation.

Please help me where I am wrong and what I need to follow.

Thanks in advance.

**Comment by mheap** [comment]
Hi @ahmedhashmi21,

It looks as though you've followed everything correctly. The issue you're seeing is a problem verifying our SSL certificate.

Could you please provide the following information:

* Which version of Windows are you using?
* Which version of PHP are you using?

**Comment by ahmedhashmi21** [comment]
Hello.

Thank you for reverting back on my query. 

My php version is **5.6.15** and I am using Windows 10. 
The error I pasted is shown in my local server but when I upload same file on production server then it displays Internal server error (error 500 ).

Please help me to resolve my problem or correct me to follow the right method.

Thanks

**Comment by mheap** [comment]
Hi @ahmedhashmi21,

I think it's an issue with your environment, which makes it tough to work out the issue. If you visit https://rest.nexmo.com/sms/json in a browser, do you get the error?

**Comment by ahmedhashmi21** [comment]
Hi,

Problem has been resolved for outbound SMS.

I am directly using "https://rest.nexmo.com/sms/json" as api using Jquery Ajax call and posting json.

from=Nexmo
text=Hello
to=91xxxxxxxxxx&
api_key=xxxxxxxx&
api_secret=xxxxxxxxxxxxxxxxxx

Now it is working fine.

Which api to call for outbound call and how to pass json for that API.

I am very near to that please help me in this then my issue will be resolved.

Thanks in advance

**Comment by mheap** [comment]
Hi @ahmedhashmi21,

To make an outbound voice call you will need to register a Nexmo application and use a private key to authenticate. We have a post on how to do this on our blog -
 https://www.nexmo.com/blog/2017/10/20/text-to-speech-voice-calls-with-php-dr/

**Comment by ahmedhashmi21** [comment]
Hello,

Thanks for providing solution but unfortunately it is still not working for me. I must have mistaken somewhere. Is it possible that I just download source code, replace keys and number and start my work.

I need basic outbound calls. please provide solution if any. 

I installed composer, ran the exact command. all commands run and execute properly but then when I go to code it is not working. 

Please help me with shortcut or any other easiest method.

Thanks

**Comment by ahmedhashmi21** [comment]
Hi Michael,

I have done all the things step by step but still getting error. please check below error log:

[01-Dec-2017 12:58:39 Etc/GMT] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/efundj6z/public_html/nex/vendor/nexmo/client/src/Client.php on line 303

I have created Nexmo voice application and also passed private.key file and application Id. path and everything is right but I am confused where I am getting wrong.

https://www.efundbook.com/nex/vendor/src/index.php

Above is the url on which I am testing. there is internal server error so I checked in error_logs file on server directory and same is pasted above.

Please reply with the best solution to resolve me issue.

Thanks

**Comment by mheap** [comment]
Hi @ahmedhashmi21,

You need PHP 5.6 minimum to use the Nexmo client library. Your server is reporting that it is using PHP version 5.4

**Comment by ahmedhashmi21** [comment]
Hi Michael,

Yes I just checked my php version is lower than required version. now I will updated my php version and retest my code. again thanks for notifying on this.

**Comment by YAHTECHGH** [comment]
Please i need help to set up an SMS reminder. DATE and TIME for the person to received, Please i need to help to setup on my Nexmo Account. PLEASE I NEED HELP THANK YOU.
