### ISSUE TITLE
Using the lang setting for calls.

### ISSUE THREAD

**Issue by benwrigley** [Nexmo/nexmo-php#97]
I wonder if the language option is available with this package yet?

I have tried:

```php
          $verification = \Nexmo::verify()->start([
                      'number' => $cleanNumber,
                      'brand' => 'Business Name',
                      'lang' => 'en-gb-male'
            ]);
```
...but I still get the US female.

Thanks

**Comment by mheap** [comment]
It should be available. I believe the parameter is named `lg`, not `lang` after reading https://developer.nexmo.com/api/verify#request

**Comment by benwrigley** [comment]
Thank you! I must have stumbled on some old documentation that said lang.

However, do you have any idea how to set the gender, it doesn't like en-gb-male.

Thanks again

**Comment by mheap** [comment]
I've not set the gender myself, but a colleague recommended the `voice` parameter:

```php
'lg' => 'en-gb',
'voice' => 'male'
```

**Comment by benwrigley** [comment]
Great idea, but no joy I'm afraid :(

I'll email Nexmo direct, thank you again!

**Comment by mheap** [comment]
@benwrigley Sorry I couldn't help more. Please do let us know when you solve the issue

**Comment by benwrigley** [comment]
@mheap turns out voice gender isn't actually released yet, they just accidentally released the documentation :)

Thanks again!

Ben
