### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by ILABUTK** [Nexmo/nexmo-php#98]
I recently used this package and found out my Nexmo account balance is running out very quickly. It turns out someone stole the the api key and secret. I have been in contact with Nexmo support. I was able to find out from the SMS log that somehow someone was able to text himself my key/secret. It seems to me there is security concerns but the tech support from Nexmo clearly denies it. 

Below is the log. A guy from Morocco did this (country code 212). 

ID | Date Received | From | To | Date Closed | Status | Error Code | Error Code Description | Price | Network | Network Name | Country | Country Name | Body
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

0D000000713D6657 | 2018-01-02 21:59:25 | sdqsD | 212643005354 | 2018-01-02 21:59:37 | DELIVRD |   | 0.06300000 | 60401 | Maroc Telecom | MA | Morocco | LOG : **MYKEY** \|**SECRET**
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

This is just to call for cautions for future users!

**Comment by mheap** [comment]
Hi @ILABUTK, sorry to hear that.

Could you provide the ticket number you've been working with support on so that I can take a look myself?

**Comment by ILABUTK** [comment]
Here it is: (#602900).

**Comment by mheap** [comment]
@ILABUTK I've taken a look at the ticket and can't see anything that indicates an issue on the Nexmo platform. I'd like to request some potentially sensitive information from you around your application/server setup so I'd recommend taking this to email if you don't mind?

**Comment by ILABUTK** [comment]
Michael, absolutely! Please email me at ilab.utk@gmail.com. I will send your the full log, along with some config in .env file etc.

**Comment by mheap** [comment]
Email sent! :)
